-- Prompt 28: expand record workflow enums (additive; never drop values)
ALTER TYPE "RecordStatus" ADD VALUE 'PENDING_CHECK';
ALTER TYPE "RecordStatus" ADD VALUE 'PENDING_VERIFICATION';
ALTER TYPE "RecordStatus" ADD VALUE 'COMPLETED';
ALTER TYPE "RecordStatus" ADD VALUE 'RETURNED_FOR_CORRECTION';
ALTER TYPE "RecordStatus" ADD VALUE 'RESUBMITTED';

ALTER TYPE "ApprovalType" ADD VALUE 'RETURN';
ALTER TYPE "ApprovalType" ADD VALUE 'REJECT';
ALTER TYPE "ApprovalType" ADD VALUE 'VOID';
ALTER TYPE "ApprovalType" ADD VALUE 'AMEND';

ALTER TYPE "NotificationType" ADD VALUE 'RECORD_RETURNED';
ALTER TYPE "NotificationType" ADD VALUE 'RECORD_CHECKED';
ALTER TYPE "NotificationType" ADD VALUE 'RECORD_PENDING_VERIFICATION';
