-- CreateEnum
CREATE TYPE "ChecklistItemType" AS ENUM ('PASS_FAIL_NA', 'ACCEPTABLE_UNACCEPTABLE_NA', 'YES_NO_NA', 'SHORT_TEXT', 'LONG_TEXT', 'NUMBER', 'TEMPERATURE', 'DATE', 'TIME', 'SINGLE_SELECT', 'PHOTO_EVIDENCE', 'SIGNATURE');

-- AlterTable
ALTER TABLE "ChecklistItem" ADD COLUMN     "correctiveActionRequiredOnFail" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "defaultResponse" TEXT,
ADD COLUMN     "isCriticalFailure" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "itemType" "ChecklistItemType" NOT NULL DEFAULT 'ACCEPTABLE_UNACCEPTABLE_NA',
ADD COLUMN     "maxValue" DOUBLE PRECISION,
ADD COLUMN     "minValue" DOUBLE PRECISION,
ADD COLUMN     "remarkRequiredOnFail" BOOLEAN NOT NULL DEFAULT false;
